# Generated by Django 5.0.1 on 2024-01-08 17:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('cpf', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Wrong DNI.', regex='^0*(\\d{1,3}(\\.?\\d{3})*)\\-?([\\dkK])$')], verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro', models.CharField(max_length=150)),
                ('placa', models.CharField(max_length=8)),
                ('ano', models.IntegerField()),
                ('laavgens', models.IntegerField(default=0)),
                ('consertos', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
