# Generated by Django 5.0.1 on 2024-01-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=12, unique=True, verbose_name='DNI'),
        ),
    ]
